### PR TITLE
Use Environment Variables for configuration

### PR DESCRIPTION
**Pull request by lswith**
Now that AWS Lambda supports environment variables for configuration, I suggest that using them is easier than your current s3 config file implementation.

### CODE REVIEW

**Comment by rlmartin** [comment]
Thanks for the contribution! I've been meaning to work ENV variables back into this project. I looked at your changes and they seem good, but I'd like to investigate a couple things first:

1. The possibility of storing values as JSON instead of string (probably not even possible)
2. What to do about encryption (i.e. SSH passwords and such)

**Comment by lswith** [comment]
yeah so the JSON isn't possible because I got this error when I tried one big `CONFIG` environment variable:
```
1 validation error detected: Value at 'environment.variables' failed to satisfy constraint: Map value must satisfy constraint: [Member must satisfy regular expression pattern: [^,]*]
```

It seems that lambda doesn't like commas in their variables.

**Comment by rlmartin** [comment]
Ok, yeah - seems like JSON.parse is a necessary evil here. I'm not sure the configHelper is really necessary, but I'll tweak that in a subsequent commit - which you can feel free to pull down if you like (or not).

**Comment by rlmartin** [comment]
Oops, now I see what you're talking about (I am testing some updates to the CF template). Need to go back and rethink this a bit...

**Comment by rlmartin** [comment]
Ok, I'm going to make the change in aws-lambda-config and add that back in here. The commas are allowed if you encrypt the config JSON - but then there is some overhead of decrypting the config before parsing the JSON. Honestly, I expected this to be easier.

**Pull request merged**
